#!/bin/bash

# Download uninstall tool
latest_release_json=$(curl -s https://api.github.com/repos/dotnet/cli-lab/releases/latest)
download_url=$(echo "$latest_release_json" | grep "browser_download_url" | grep "osx-x64.tar.gz" | cut -d '"' -f 4)
filename=$(basename "$download_url")
curl -L -o "$filename" "$download_url"

# Prepare uninstall tool
tar -xzf "$filename"
uninstall_tool_path=$(find . -name dotnet-core-uninstall)
chmod +x "$tool_path"

# Perform uninstall
"$uninstall_tool_path" remove --yes --force --all --aspnet-runtime
"$uninstall_tool_path" remove --yes --force --all --hosting-bundle
"$uninstall_tool_path" remove --yes --force --all --runtime
"$uninstall_tool_path" remove --yes --force --all --sdk
