name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Run example 'run-app'
      run: cargo run --example run-app --verbose
    - name: Run example 'call-managed-function'
      run: cargo run --example call-managed-function --verbose
    - name: Run example 'passing-parameters'
      run: cargo run --example passing-parameters --verbose
